version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: customer_app_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: quanlykhachhang
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./src/main/resources/database/mysql-schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./src/main/resources/database/sample-users.sql:/docker-entrypoint-initdb.d/02_users.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
